import { createContext, useContext } from 'react';

/**
 * The BHW app's language, its dictionary, and the hook that reads them — split
 * from the provider in `BhwLanguageContext.tsx` since a component-exporting file
 * can't also export a hook without breaking Fast Refresh.
 */

export type Language = 'en' | 'fil';

export const filipino: Record<string, string> = {
  'Project MABISA': 'Proyektong MABISA',
  'BHW Mobile': 'BHW Mobile',
  'Resident profiling, health assessment, supply logging, and offline sync.': 'Pagtatala ng residente, pagsusuri ng kalusugan, pamamahagi ng suplay, at offline sync.',
  'Online': 'Online',
  'Offline': 'Offline',
  'Logout': 'Mag-logout',
  'Status': 'Kalagayan',
  'Resident': 'Residente',
  'Health': 'Kalusugan',
  'Supply': 'Suplay',
  'Profile': 'Profile',
  'Account': 'Account',
  'Signed in as': 'Naka-sign in bilang',
  'Role': 'Tungkulin',
  'Barangay Health Worker': 'Barangay Health Worker',
  'Records on this device': 'Mga tala sa device na ito',
  'Appearance': 'Anyo',
  'Log out of MABISA?': 'Mag-logout sa MABISA?',
  'Make sure pending records are synchronized before leaving this device.': 'Tiyaking na-sync ang mga nakabinbing tala bago umalis sa device na ito.',
  'Stay logged in': 'Manatiling naka-login',
  'Log out': 'Mag-logout',
  'Device status': 'Kalagayan ng device',
  'Ready to sync records': 'Handang mag-sync ng mga tala',
  'Encoding works offline': 'Maaaring magtala kahit offline',
  'Connection': 'Koneksyon',
  'Sync status': 'Kalagayan ng sync',
  'Queue': 'Nakahilera',
  'Synced': 'Naka-sync',
  'Pending Sync': 'Naghihintay ng sync',
  'Sync Failed': 'Hindi nag-sync',
  'Check for Updates': 'Tingnan ang Updates',
  'Push Local Changes': 'I-sync ang mga Tala',
  'Retry Sync': 'Subukang Muli',
  'Syncing...': 'Nagsi-sync...',
  'Last synced': 'Huling na-sync',
  'This device has not completed a sync yet.': 'Wala pang natatapos na sync ang device na ito.',
  'Households': 'Mga Sambahayan',
  'Registered dwellings': 'Rehistradong tirahan',
  'Individuals': 'Mga Residente',
  'Local profiles': 'Mga profile sa device',
  'Assessments': 'Mga Pagsusuri',
  'Health records': 'Mga tala ng kalusugan',
  'Released': 'Naipamahagi',
  'Supply logs': 'Mga tala ng suplay',
  'BHW workflow': 'Gawain ng BHW',
  'Recent Profiles': 'Mga Bagong Profile',
  'Saved Offline': 'Naka-save Offline',
  'No local profiles yet': 'Wala pang profile sa device',
  'Register a household to start the offline-first BHW workflow.': 'Magrehistro ng sambahayan upang makapagsimula.',
  'Recent checks': 'Mga Bagong Pagsusuri',
  'Health Assessments': 'Mga Pagsusuri sa Kalusugan',
  'No assessments yet': 'Wala pang pagsusuri',
  'Saved health assessments will appear here.': 'Dito makikita ang mga na-save na pagsusuri.',
  'Household Profiling': 'Pagtatala ng Sambahayan',
  'New Household Registration': 'Bagong Rehistro ng Sambahayan',
  'Household Information': 'Impormasyon ng Sambahayan',
  'Household Number': 'Numero ng Sambahayan',
  'None': 'Wala',
  'Local Water District': 'Lokal na Water District',
  'Deep Well': 'Malalim na Balon',
  'Artesian Well': 'Balong Artesian',
  'Bottled/Purified': 'Bote o Purified Water',
  'Spring / River': 'Bukal o Ilog',
  'Water-sealed (Flush)': 'Water-sealed o Flush',
  'Pit Latrine': 'Hukay na Palikuran',
  'Shared / Communal': 'Pinagsasaluhan',
  'Backyard Garden': 'Gulayan sa Bakuran',
  'Livestock / Poultry': 'Hayop o Manok',
  'Farming': 'Pagsasaka',
  'Primary Water Source(s)': 'Pangunahing Pinagmumulan ng Tubig',
  'Toilet Facility': 'Uri ng Palikuran',
  'Food Production': 'Produksyon ng Pagkain',
  'Household Members': 'Mga Miyembro ng Sambahayan',
  'Member': 'Miyembro',
  'Head': 'Puno',
  'First Name': 'Pangalan',
  'Middle Name': 'Gitnang Pangalan',
  'Last Name': 'Apelyido',
  'Birthdate': 'Petsa ng Kapanganakan',
  'Sex': 'Kasarian',
  'Female': 'Babae',
  'Male': 'Lalaki',
  'This person is a Household Head': 'Ang taong ito ang puno ng sambahayan',
  'This person is a household head': 'Ang taong ito ang puno ng sambahayan',
  'Out-of-school youth': 'Kabataang hindi nag-aaral',
  'Pregnant, nursing, or using family planning': 'Buntis, nagpapasuso, o gumagamit ng family planning',
  'Occupation': 'Hanapbuhay',
  'Relationship to Household Head': 'Kaugnayan sa Puno ng Sambahayan',
  'Spouse': 'Asawa',
  'Child': 'Anak',
  'Parent': 'Magulang',
  'Sibling': 'Kapatid',
  'Other Relative': 'Ibang kamag-anak',
  'Unrelated': 'Hindi kamag-anak',
  'Educational Attainment': 'Natapos na Pag-aaral',
  'PhilHealth Number': 'Numero ng PhilHealth',
  'Dashes and spaces are fine — only the digits are saved.': 'Puwede ang gitling at espasyo — ang mga numero lang ang ise-save.',
  '(Not specified)': '(Hindi tinukoy)',
  'Elementary': 'Elementarya',
  'High School': 'Hayskul',
  'Senior High School': 'Senior High School',
  'Vocational': 'Bokasyonal',
  'College': 'Kolehiyo',
  'Post-graduate': 'Post-graduate',
  '+ Add Another Member': '+ Magdagdag ng Miyembro',
  'Add another member': 'Magdagdag ng Miyembro',
  'Body mass index': 'Body mass index',
  'Enter weight and height': 'Ilagay ang timbang at taas',
  'Save Complete Household': 'I-save ang Sambahayan',
  'Saving Offline...': 'Sine-save Offline...',
  'Assessment': 'Pagsusuri',
  'Health Assessment': 'Pagsusuri sa Kalusugan',
  'Ready': 'Handa',
  'Needs Profile': 'Kailangan ng Profile',
  'Search Profile': 'Maghanap ng Profile',
  'Search by name...': 'Maghanap gamit ang pangalan...',
  'Individual': 'Residente',
  'Select a resident': 'Pumili ng residente',
  'Searching...': 'Naghahanap...',
  'No resident found': 'Walang nahanap na residente',
  'Search item...': 'Maghanap ng aytem...',
  'No item found': 'Walang nahanap na aytem',
  'Assessment Date': 'Petsa ng Pagsusuri',
  'Weight (kg)': 'Timbang (kg)',
  'Height (cm)': 'Taas (cm)',
  'Waiting for measurements': 'Naghihintay ng sukat',
  'Save Assessment': 'I-save ang Pagsusuri',
  'Inventory': 'Imbentaryo',
  'Disburse Supplies': 'Ipamahagi ang Suplay',
  'Residents Ready': 'Handa ang mga Residente',
  'Stock Available': 'May Stock',
  'Empty Stock': 'Walang Stock',
  'Item': 'Aytem',
  'Quantity': 'Dami',
  'Date': 'Petsa',
  'Save Disbursement': 'I-save ang Pamamahagi',
  'Register a household before recording a health assessment.': 'Magrehistro muna ng sambahayan bago gumawa ng pagsusuri.',
  'Register a household before disbursing supplies.': 'Magrehistro muna ng sambahayan bago mamahagi ng suplay.',
  'Admin must sync inventory items before disbursement.': 'Kailangang i-sync muna ng admin ang imbentaryo.',
  'Select a resident.': 'Pumili ng residente.',
  'Assessment date is required.': 'Kailangan ang petsa ng pagsusuri.',
  'Enter a weight from 1 to 300 kg.': 'Maglagay ng timbang mula 1 hanggang 300 kg.',
  'Enter a height from 30 to 250 cm.': 'Maglagay ng taas mula 30 hanggang 250 cm.',
  'Select an inventory item.': 'Pumili ng aytem sa imbentaryo.',
  'Enter a quantity of at least 1.': 'Maglagay ng dami na hindi bababa sa 1.',
  'Disbursement date is required.': 'Kailangan ang petsa ng pamamahagi.',
  'Action Required:': 'Kailangang Ayusin:',
  'Household number is required.': 'Kailangan ang numero ng sambahayan.',
  'First name is required.': 'Kailangan ang pangalan.',
  'Last name is required.': 'Kailangan ang apelyido.',
  'Birthdate is required.': 'Kailangan ang petsa ng kapanganakan.',
  'Assign one household head.': 'Magtalaga ng isang puno ng sambahayan.',
  'Select at least one water source.': 'Pumili ng kahit isang pinagmumulan ng tubig.',
  'Select at least one toilet facility.': 'Pumili ng kahit isang uri ng palikuran.',
  'Select at least one food-production option.': 'Pumili ng kahit isang paraan ng produksyon ng pagkain.',

  // Duplicate warning — the Filipino must read as a question, never a refusal.
  'Someone here may already be registered': 'May kaparehong nakatala na',
  'Check these records before saving. If this is a different person, say so and the app will keep your reason with the new record.':
    'Suriin ang mga talang ito bago mag-save. Kung ibang tao ito, sabihin at itatabi ng app ang inyong dahilan kasama ng bagong tala.',
  'Same name and birthdate': 'Parehong pangalan at kaarawan',
  'Same name': 'Parehong pangalan',
  'Why is this a different person?': 'Bakit ibang tao ito?',
  'Saved with the record so an administrator can see who decided this and why.':
    'Itatabi kasama ng tala para makita ng administrator kung sino ang nagdesisyon at bakit.',
  'Go back and edit': 'Bumalik at baguhin',
  'Not the same person — save': 'Hindi pareho — i-save',

  // Resident registry and detail.
  'Registry': 'Talaan',
  'Residents': 'Mga residente',
  'Search residents': 'Maghanap ng residente',
  'Back to residents': 'Bumalik sa mga residente',
  'Opening record...': 'Binubuksan ang tala...',
  'Resident not on this device': 'Wala sa device na ito ang residente',
  'They may belong to another purok, or their record has not synced down yet.':
    'Maaaring nasa ibang purok sila, o hindi pa nakababa ang kanilang tala.',
  'Household Head': 'Puno ng Sambahayan',
  'Household': 'Sambahayan',
  'Age': 'Edad',
  'years old': 'taong gulang',
  'Yes': 'Oo',
  'No': 'Hindi',
  'Edit profile': 'Baguhin ang profile',
  'Cancel': 'Kanselahin',
  'Save changes': 'I-save ang binago',
  'Saved over a duplicate warning': 'Na-save kahit may babala ng kaparehong tala',
  'Supplies Released': 'Mga Ipinamahaging Suplay',
  'No supplies released': 'Walang ipinamahaging suplay',
  'Supply releases to this resident appear here.': 'Lalabas dito ang mga suplay na ibinigay sa residenteng ito.',
  'Item not on this device': 'Wala sa device na ito ang aytem',

  // Idle lock. Nothing here may suggest work was lost, because none was.
  'Screen locked': 'Naka-lock ang screen',
  'Nothing was lost. Your records are still on this device.':
    'Walang nawala. Nasa device pa rin ang inyong mga tala.',
  'record(s) still saved on this device.': 'na tala ang nakasave pa rin sa device na ito.',
  'Continue': 'Magpatuloy',
};

export type BhwLanguageValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (text: string) => string;
  isFilipino: boolean;
};

export const BhwLanguageContext = createContext<BhwLanguageValue | null>(null);

export function useBhwLanguage() {
  const value = useContext(BhwLanguageContext);
  if (!value) throw new Error('useBhwLanguage must be used within BhwLanguageProvider');
  return value;
}
